[디자인] Notice.kt 와 NoticeDetail.kt 디자인 확인 요청
Team-Crackdown/TAVE-Android pull request #11
Opened 2023-06-26 13:55 UTC by Luna828

안녕하세요 @KanuKim97 님!~
Notice.kt 와 NoticeDetail.kt 디자인을 완료하여 PR을 요청드립니다~
빠른 확인과 검토 부탁드립니다!

### 작업 내역

1.  NoticeTechLetterItems 생성
2.  Notice 페이지에 LazyColumn, LazyRow 를 사용한 Scrollview 제작
3.  NoticeDetailLazyGridsPics (image view) 생성
4.  NoticeDetail 페이지에 LazyGrid 제작

2023-06-26 14:04 UTC, KanuKim97 commented
안녕하세요! @Luna828 님! 
PR 요청 확인했습니다!
수정해야할 점이 좀 있네요?
1. 우선 Text()에 하드코딩이 되어있습니다! 이 내용을 변수로 바꾸어주세요!
2. Notice에 들어가는 subItems는 list로 읽어와야 합니다! 그러니 이것 또한 변수로 변경 시 자료형에 유의하여 변경해주세요!
3. Image()를 landscapist-glide를 사용한 ImageLoader()로 변경해주세요!
  - 단! 여기서 주의해야할 점은 불러운 리스트의 사진이 없을 경우 기존 drawable 폴더의 cover이미지로 로딩 되어야합니다!
이 정도만 수정되면 될 거 같습니다! @Luna828 님

2023-06-26 14:11 UTC, KanuKim97 requested changes
@Luna828 님! 리뷰 작성했습니다 확인해주세요!

2023-06-26 14:11 UTC, KanuKim97 commented on TAVE/app/src/main/java/com/example/tave/items/notice/NoticeSubItems.kt
> +fun NoticeSubItems(
subItemTitle: String,
subItemWriter: String,
subItemTimeStamp: String
는 어차피 List로 받아야 하는 항목들이니 List로 한 번에 처리하시는게 어떨까요?

2023-06-26 14:11 UTC, KanuKim97 commented on TAVE/app/src/main/java/com/example/tave/items/notice/NoticeTechLetterItems.kt
> +@Preview(showBackground = true, showSystemUi = true)
showSystemUi = true를 사용하셨는데 Item이기 때문에 굳이 필요한 이유가 없어보입니다.
따라서 이 옵션은 제거해도 괜찮아 보이네요

2023-06-26 14:11 UTC, KanuKim97 commented on TAVE/app/src/main/java/com/example/tave/items/noticeDetail/NoticeDetailLazyGridsPics.kt
> +                        .clip(RoundedCornerShape(5.dp)),
Shape.kt를 활용해 보시는 건 어떤가요?

2023-06-26 14:11 UTC, KanuKim97 commented on TAVE/app/src/main/java/com/example/tave/MainActivity.kt
> -                        LoginPage(applicationContext, navController)
이거는 잘하셨네요! @Luna828 !
applicationContext를 제거 하셨는데 구체적인 이유가 있을까요?

2023-06-26 14:57 UTC, Luna828 commented on TAVE/app/src/main/java/com/example/tave/items/noticeDetail/NoticeDetailLazyGridsPics.kt
> +                        .clip(RoundedCornerShape(5.dp)),
@KanuKim97 님! 변경완료하였습니다!

2023-06-26 14:57 UTC, Luna828 commented on TAVE/app/src/main/java/com/example/tave/items/notice/NoticeTechLetterItems.kt
> +@Preview(showBackground = true, showSystemUi = true)
@KanuKim97 님, 피드백에 따라서 제거 완료하였습니다~

2023-06-26 14:57 UTC, Luna828 commented on TAVE/app/src/main/java/com/example/tave/items/notice/NoticeSubItems.kt
> +fun NoticeSubItems(
@KanuKim97 님, 피드백 감사합니다! 
빠른 시일 내로 변경해서 다시 수정해 올리겠습니다~

2023-06-27 00:07 UTC, Luna828 commented on TAVE/app/src/main/java/com/example/tave/MainActivity.kt
> -                        LoginPage(applicationContext, navController)
@KanuKim97 좋은 질문 감사합니다! 
Application Context는 application lifecycle을 따라갑니다. 
그러므로 app이 실행되어 종료될 때까지 계속 객체가 살아나 있습니다. 

하지만, LoginPage같은 경우 로그인이 된 이후로부터는 객체가 더이상 살아나있지 않아도 된다고 판단하여 제거하게 되었습니다!

2023-06-27 09:43 UTC, KanuKim97 approved these changes

2023-06-27 09:45 UTC, merged

2023-06-27 09:46 UTC, KanuKim97 commented
[17001e6](https://github.com/Team-Crackdown/TAVE-Android/pull/11/commits/17001e6d1ef9f442053986da5be0c3b00604e1ce) 커밋으로 인한  Merge